import type { PhysicsConfig, Room, Terrain } from "../types";

export const INITIAL_ROOMS: Room[] = [
  {
    id: "sala",
    name: "Sala / Estar",
    type: "living",
    x: 6.0,
    y: 7.0,
    w: 5.0,
    h: 4.0,
    targetW: 5.0,
    targetH: 4.0,
    floor: 0,
    color: "#FEF3C7",
    connections: ["cocina", "pasillo"],
    openings: [
      { id: "win_sala", type: "window", side: "bottom", offset: 0.5, width: 2.0 },
      { id: "door_sala_pasillo", type: "door", side: "top", offset: 0.8, width: 0.9 },
    ],
    furniture: [
      { id: "s1", type: "sofa", name: "Sofá Familiar", x: 0, y: -1.2, w: 2.0, h: 0.9, rotation: 0 },
      { id: "s2", type: "tv", name: "Mueble TV", x: 0, y: 1.5, w: 1.6, h: 0.45, rotation: 180 },
      { id: "s3", type: "plant", name: "Ficus Maceta", x: -2.0, y: -1.2, w: 0.5, h: 0.5, rotation: 0 },
    ],
  },
  {
    id: "cocina",
    name: "Cocina Americana",
    type: "kitchen",
    x: 3.5,
    y: 11.5,
    w: 3.5,
    h: 3.0,
    targetW: 3.5,
    targetH: 3.0,
    floor: 0,
    color: "#FEE2E2",
    connections: ["sala"],
    openings: [{ id: "win_coc", type: "window", side: "left", offset: 0.5, width: 1.2 }],
    furniture: [
      { id: "k1", type: "fridge", name: "Nevera", x: -1.2, y: -0.9, w: 0.8, h: 0.8, rotation: 90 },
      { id: "k2", type: "stove", name: "Encimera", x: 0, y: -1.0, w: 0.75, h: 0.6, rotation: 0 },
      { id: "k3", type: "sink", name: "Fregadero", x: 1.2, y: -0.9, w: 0.7, h: 0.55, rotation: 270 },
    ],
  },
  {
    id: "dormitorio",
    name: "Dormitorio Principal",
    type: "bedroom",
    x: 8.5,
    y: 13.0,
    w: 4.5,
    h: 4.0,
    targetW: 4.5,
    targetH: 4.0,
    floor: 0,
    color: "#DBEAFE",
    connections: ["pasillo", "bano_privado"],
    openings: [
      { id: "win_dorm", type: "window", side: "right", offset: 0.5, width: 1.5 },
      { id: "door_dorm_bano", type: "door", side: "top", offset: 0.2, width: 0.8 },
    ],
    furniture: [
      { id: "b1", type: "bed", name: "Cama King", x: 0, y: 0.5, w: 1.8, h: 2.0, rotation: 180 },
      { id: "b2", type: "wardrobe", name: "Ropero", x: -1.8, y: -1.0, w: 1.5, h: 0.6, rotation: 90 },
    ],
  },
  {
    id: "pasillo",
    name: "Pasillo Distribuidor",
    type: "corridor",
    x: 6.0,
    y: 11.5,
    w: 1.2,
    h: 4.0,
    targetW: 1.2,
    targetH: 4.0,
    floor: 0,
    color: "#F3F4F6",
    connections: ["sala", "dormitorio", "bano"],
    openings: [{ id: "door_pas_bano", type: "door", side: "left", offset: 0.8, width: 0.8 }],
    furniture: [],
  },
  {
    id: "bano",
    name: "Baño Completo",
    type: "bathroom",
    x: 3.5,
    y: 15.5,
    w: 2.5,
    h: 2.0,
    targetW: 2.5,
    targetH: 2.0,
    floor: 0,
    color: "#E0F2FE",
    connections: ["pasillo"],
    openings: [{ id: "win_bano", type: "window", side: "left", offset: 0.3, width: 0.6 }],
    furniture: [
      { id: "ba1", type: "toilet", name: "Inodoro", x: -0.8, y: -0.4, w: 0.45, h: 0.7, rotation: 90 },
      { id: "ba2", type: "sink", name: "Lavabo", x: -0.2, y: -0.6, w: 0.6, h: 0.5, rotation: 0 },
      { id: "ba3", type: "shower", name: "Ducha", x: 0.8, y: 0.5, w: 0.9, h: 0.9, rotation: 0 },
    ],
  },
  {
    id: "bano_privado",
    name: "Baño Suite",
    type: "bathroom",
    x: 8.5,
    y: 17.0,
    w: 2.2,
    h: 1.6,
    targetW: 2.2,
    targetH: 1.6,
    floor: 0,
    color: "#E0F2FE",
    connections: ["dormitorio"],
    openings: [{ id: "win_bano_p", type: "window", side: "right", offset: 0.5, width: 0.6 }],
    furniture: [
      { id: "bp1", type: "toilet", name: "Inodoro", x: -0.6, y: -0.2, w: 0.45, h: 0.7, rotation: 90 },
      { id: "bp2", type: "sink", name: "Lavamanos", x: 0.4, y: -0.4, w: 0.6, h: 0.5, rotation: 0 },
    ],
  },
];

export const INITIAL_TERRAIN: Terrain = {
  width: 12.0,
  length: 20.0,
  setbackFront: 4.0,
  setbackBack: 2.0,
  setbackLeft: 1.5,
  setbackRight: 1.5,
  hasPerimeterWall: true,
  entrySide: "front",
  northAngleDeg: 0,
  hemisphere: "south",
  levels: 1,
};

export const INITIAL_PHYSICS_CONFIG: PhysicsConfig = {
  attractionStrength: 4.5,
  repulsionStrength: 7.0,
  boundaryStrength: 5.5,
  gridSnap: true,
  gridSize: 0.1,
  running: false,
  corridorAlignment: 3.5,
};
